package org.ferpin.bloques.nlp;

public enum Concept {
    THEN, NO, NOTHING, FLOOR, IF, COLOR, BE, SIZE, ENTITY, ATTACH, RULE,
    DETACH, FEATURE, BLOCK, ABOVE, TYPE, PRISM, PUT, SET, QUIT, TAKEOUT, EXCEPTIONS, QUESTIONS, WRITE
}
